apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 99999
cgroupDriver: "systemd"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.18.0
networking:
  dnsDomain: cluster.local
  podSubnet: "{{ kube_pod_cidr }}"
  serviceSubnet: {{ kube_svc_cidr }}
controllerManager:
  extraArgs:
    node-cidr-mask-size: "{{ kube_pod_cidr | ipaddr('prefix') }}"
apiServer:
  certSANs:
  - "{{ groups['master'][0] }}"
  - "analogsea.ca"
  - "172.107.176.13"
  extraArgs:
    service-node-port-range: 1-60000
    feature-gates: "VolumeSnapshotDataSource=true,VolumePVCDataSource=true"
