- hosts:        all
  gather_facts: no
  become:       yes
  become_user:  root
  vars_files:
    - ./vars/vars.yaml
  tasks:
  - name: Restart docker service
    service:
      name: docker
      state: restarted
  - name:  reset
    shell: |
      rm -rf /root/.kube
      rm -rf /var/lib/etcd
      kubeadm reset -f
      iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
    args:
      warn: false
  - name: Reboot after reset
    reboot:
      reboot_timeout: 3600
