- hosts:              all
  gather_facts:       no
  become:             yes
  become_user:        root
  vars_files:
    - ./vars/vars.yaml
  tasks:
  - name:             Restart docker service
    service:
      name:           docker
      state:          restarted
  - name:             Reset kubeadm
    shell:            |
      rm -rf /root/.kube
      rm -rf /var/lib/etcd
      kubeadm reset -f
      iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
    args:
      warn:           false

  - name: Unhold packages
    dpkg_selections:
      name: "{{ item }}"
      selection: install
    loop: "{{ packages|flatten(levels=1) }}"
    vars:
        packages:
          - docker-ce
          - kubelet
          - kubeadm
          - kubectl
    when: unhold is not undefined

  - name:             Reboot after reset
    reboot:
      reboot_timeout: 3600
    when:             reboot is not undefined
